In [43]:
""" 
Created on FRI JAN 18 2019
 
MTS Program that graphs difference in mahalanobis distances, as well as an MTS 
 
@author: Naqib, revised: Taehee 
""" 

from __future__ import print_function 
import numpy as np 
import matplotlib as plt 
import copy 
import math
import csv
import pandas as pd
from sklearn import preprocessing

In [44]:
OKdata=pd.read_csv('C:/Users/mando/Desktop/ssd/diff.csv',encoding='utf-8' ) # SAM2데이터 from 익산1월
OKdata1=OKdata.iloc[:,2:4]
OKdata2=OKdata.iloc[:,7]
OKdata3=pd.concat([OKdata1,OKdata2],1)


In [45]:
k=OKdata3.shape[1] # 총 컬럼의 수, k값 구하기
k

3

In [67]:
scaled_df_ok=(OKdata3-OKdata3.mean())/OKdata3.std()
OKdata_corr=scaled_df_ok.corr() # 상관계수 구하기  / 이게 데이터에따라 다름!!!!
cor =np.linalg.inv(OKdata_corr) # 상관계수의 역함수
print(cor)
j=np.arange(0,len(scaled_df_ok),1)
scaled_df_ok=np.array(scaled_df_ok)

[[ 1.11146014 -0.28656468  0.19200134]
 [-0.28656468  1.07587065 -0.00488907]
 [ 0.19200134 -0.00488907  1.03515411]]


In [68]:
scaled_df_ok.shape

(81028, 3)

In [70]:
MD_result=[]
for i in j :
    okdata_matrix=scaled_df_ok[[i]]
    #print(NGdata_matrix)
    okdata_t=scaled_df_ok[i].transpose()
    #print(NGdata_t)
    MD_squre1=np.dot(okdata_matrix,cor)/k
    # print(MD_squre1.shape)
    MD_squre2=np.dot( MD_squre1,okdata_t )
    MD_squre3=np.asscalar(MD_squre2)
    # MD_squre3_5=math.sqrt(MD_squre2)    D값
    MD_result.append(MD_squre3)

In [71]:
ok_mean=np.mean(MD_result)
ok_mean  # 평균값 확인

0.9999876585871612

In [73]:
OKdata['MD']=MD_result
OKdata.to_csv('C:/Users/mando/Desktop/ssd/diff_result2.csv')